import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   <>
     <head>
      <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap"
        />
    </head>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
   </>
  )
}
